# AUTO-DEPLOY updated path
name: Deploy to Kubernetes (Dev)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply Kustomize dev (force correct directory)
        run: |
          echo "Current path:"
          pwd
          echo "Listing files:"
          ls -la

          echo ">>> ENTERING k8s-demo/"
          cd k8s-demo

          echo "Now in:"
          pwd
          echo "Listing:"
          ls -la

          echo ">>> Running kubectl apply..."
          kubectl apply -k k8s/overlays/dev
