# AUTO-DEPLOY updated path
name: Deploy to Kubernetes (Dev)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: DIAG — покажи где мы вообще находимся
        run: |
          echo ">>> PWD:"
          pwd
          echo ">>> LS:"
          ls -la
          echo ">>> ИЩУ overlays:"
          find . -maxdepth 4 -type d -name overlays || true

      - name: Apply Kustomize dev
        run: kubectl apply -k ./k8s/overlays/dev
