# AUTO-DEPLOY updated path
name: Deploy to Kubernetes (Dev)

on:
  workflow_dispatch:   # запуск вручную

jobs:
  deploy:
    runs-on: self-hosted  # наш локальный runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CD into real repo folder
        run: |
          echo "=== CURRENT LOCATION ==="
          pwd
          echo "=== AVAILABLE FOLDERS ==="
          ls -la

          echo ">>> MOVING INTO k8s-demo/"
          cd k8s-demo

          echo "=== NOW HERE ==="
          pwd
          ls -la

          echo ">>> APPLYING KUSTOMIZE"
          kubectl apply -k k8s/overlays/dev
