# AUTO-DEPLOY updated path
name: Deploy to Kubernetes (Dev)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: k8s-demo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply Kustomize dev
        run: kubectl apply -k ./k8s/overlays/dev
