# AUTO-DEPLOY updated path
name: Deploy to Kubernetes (Dev)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show workspace path
        run: |
          echo "Current path: $(pwd)"
          echo "Listing files:"
          ls -la

      - name: Apply Kustomize dev
        working-directory: k8s-demo
        run: |
          echo "Switched into: $(pwd)"
          kubectl apply -k ./k8s/overlays/dev
