# AUTO-DEPLOY updated path
name: Deploy to Kubernetes (Dev)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show context
        run: |
          pwd
          ls -la

      - name: Apply Kustomize dev
        run: |
          echo ">>> Deploying from $(pwd)"
          kubectl apply -k ./k8s/overlays/dev
