# AUTO-DEPLOY updated path
name: Deploy to Kubernetes (Dev)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply Kustomize dev (force correct directory)
        run: |
          echo "=== CURRENT PATH ==="
          pwd
          echo "=== FILES HERE ==="
          ls -la

          echo ">>> ENTERING k8s-demo/"
          cd k8s-demo

          echo "=== NOW IN ==="
          pwd
          echo "=== FILES HERE ==="
          ls -la

          echo ">>> RUNNING: kubectl apply -k k8s/overlays/dev"
          kubectl apply -k k8s/overlays/dev
