# AUTO-DEPLOY updated path
name: Deploy to Kubernetes (Dev)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug — show current workspace
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "Files in workspace:"
          ls -la "$GITHUB_WORKSPACE"

      - name: Apply Kustomize dev
        run: |
          echo "Applying from: $GITHUB_WORKSPACE/k8s/overlays/dev"
          kubectl apply -k "$GITHUB_WORKSPACE/k8s/overlays/dev"
